# Generated by Django 5.2.4 on 2025-07-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('IE', 'IT Equipment'), ('MB', 'Mobiles Devices'), ('OF', 'Office Furnitures'), ('OS', 'Office Supplies'), ('NE', 'Network Equipment'), ('SL', 'Software & Licenses'), ('EE', 'Electrical Equipement'), ('SS', 'Security Systems'), ('MISC', 'Miscellaneous')], max_length=50, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
