# Generated by Django 5.2.6 on 2025-10-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_order_product_delete_asset_order_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('emai', models.EmailField(max_length=254)),
                ('department', models.CharField(choices=[('IT', 'Information Technology'), ('HR', 'Human Resource'), ('ADMIN', 'Administrative'), ('FINANCE', 'Accounting & Finance'), ('OPS', 'Operational')], max_length=50, null=True)),
                ('position', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('phone_number', models.CharField(max_length=11, null=True)),
                ('start_date', models.DateField(null=True)),
                ('location', models.CharField(max_length=200)),
                ('notes', models.TextField(null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='Asset',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='asset',
        ),
    ]
