# Generated by Django 5.2.6 on 2025-10-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_staff_rename_product_asset_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='quantity',
        ),
        migrations.AddField(
            model_name='asset',
            name='brand',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='date_purchase',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='date_warranty',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='price',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='sn',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('In Use', 'In Use'), ('Under Maintenance', 'Under Maintenance'), ('Retired', 'Retired')], default='Available', max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='supplier',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='track_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
