# Generated by Django 5.2.6 on 2025-10-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('HR', 'Human Resource'), ('ADMIN', 'Administrative'), ('FINANCE', 'Accounting & Finance'), ('OPS', 'Operational')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
